FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV FLASK_APP=app:create_app
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:create_app()", "-w", "4", "--worker-class", "sync"]
