from flask import Blueprint, render_template, redirect, url_for
from models.war import War
from models.event import Event
from extensions import db
from datetime import datetime

# Blueprint initialized with the template folder
wars_bp = Blueprint("wars", __name__, template_folder="templates")

@wars_bp.route("/<int:war_id>")
@wars_bp.route("/<int:war_id>/<string:date_str>")
def show_war(war_id, date_str=None):
    """
    Main Map View. 
    If no date is provided, it automatically finds the latest date with data.
    """
    war = War.query.get_or_404(war_id)
    
    # 1. THE AUTOMATIC CHASE LOGIC
    # If the user just goes to /wars/1, find the most recent event in the DB
    if not date_str or date_str == "latest" or date_str == "mm/dd/yyyy":
        latest_event = Event.query.filter_by(war_id=war_id).order_by(Event.event_date.desc()).first()
        
        if latest_event:
            # Redirect to the specific day found (e.g., /wars/1/2011-03-06)
            # url_for('wars.show_war', ...) ensures the URL is built correctly
            return redirect(url_for('wars.show_war', war_id=war_id, date_str=latest_event.event_date.strftime('%Y-%m-%d')))
        else:
            # Fallback if the database is completely empty
            date_str = "2011-03-06"

    # 2. RENDER THE MAP
    # initial_date is passed to the JavaScript in war.html
    # war_start is the minimum date the user can navigate to
    war_start = war.start_date.strftime('%Y-%m-%d') if war.start_date else "2011-03-06"
    return render_template('war.html', war=war, initial_date=date_str, war_start=war_start)

@wars_bp.route('/event/<string:event_slug>')
def event_permalink(event_slug):
    """
    Permalink for a specific piece of evidence. 
    Allows users to share a direct link to a single YouTube video/post.
    """
    # Look up the event by the 'key' (the unique slug generated by the AI)
    event = Event.query.filter_by(hash_key=event_slug).first_or_404()
    
    # Render the war template, but tell JS to focus on this specific event
    return render_template('war.html', 
                           war=event.war, 
                           initial_date=event.event_date.strftime('%Y-%m-%d'),
                           focus_event_id=event.id)